title: Timmy White # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mobile Application Developer of 10 years, with a Master's degree in Computer Science from Georgia Tech. Experienced in iOS, Android, and Unity3D development.
  <br><br>
  <a href="https://www.linkedin.com/in/timothy-white-37195b193/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
